### ISSUE TITLE
Connecting LN-101 

### ISSUE THREAD

**Issue by grndctrl2majtom** [nikwl/dynamixel-shield-toolbox#2]
Hi I'm having some issues connecting the LN-101 to the shield... How do you read it from the serial monitor?

**Comment by grndctrl2majtom** [comment]
I figured it out, I can print using the serial converter. I just can figure out how to write commands.

**Comment by nikwl** [comment]
Hi, sorry for the long delay.
You should be able to use the serial communicator just like a normal serial connection, for both reading and writing. If you're not able to write then that's an indication that something isn't set up correctly.
